<div style="background-color: #9D2235; color: white; padding: 10px; ">
  
# Python Pandas Library
    
</div>

# Python Data Science Libraries

## Pandas
Pandas is a powerful library for data manipulation and analysis in Python. It provides versatile data structures like DataFrame and Series for working with tabular data. The library offers comprehensive tools for:
- Data cleaning
- Data aggregation
- Data transformation

## NumPy
NumPy is the fundamental numerical computing library for Python. Key features include:
- Support for multi-dimensional arrays and matrices
- Efficient mathematical functions for numerical operations
- High-performance numerical computing capabilities

## Matplotlib
Matplotlib is a comprehensive data visualization library for Python, enabling:
- Creation of static, animated, and interactive visualizations
- Wide range of plot types and chart styles
- Flexible and detailed data representation

## Seaborn
Seaborn is a statistical data visualization library built on top of Matplotlib. It provides:
- High-level interface for creating statistical graphics
- Enhanced visual aesthetics
- Easy-to-use statistical plot generation
- Improved data visualization capabilities

## SciPy
SciPy is a collection of scientific computing algorithms, including:
- Linear algebra
- Differential equations
- Numerical integration
- Optimization techniques
- Statistical functions

## Scikit-learn
Scikit-learn is a machine learning library for Python that simplifies:
- Classification and regression tasks
- Clustering algorithms
- Model selection
- Data preprocessing
- Building and evaluating machine learning models

<div style="background-color: #9DC9D5; padding: 10px;">
Loading python libraries
</div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

In [2]:
import pandas as pd

print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

<div style="background-color: #9DC9D5; padding: 10px;">
    <h3>Panda Series</h3>

#### Definition
Series are like columns in Excel:
- One-dimensional labeled array
- Created from lists, arrays, or dictionaries

#### Basic Syntax
```python
pd.Series(data, index=labels)
```

</div>

In [3]:
#Creating panda series from dictionary
import pandas as pd

data = {'pears': [5, 7, 11, 13], 'oranges':[12, 2, 3, 5]}

#Pass this data to DataFrame constructor

df = pd.Series(data)
df

pears      [5, 7, 11, 13]
oranges     [12, 2, 3, 5]
dtype: object

<div style="background-color: #9DC9D5; padding: 10px;">
    <h3>Pandas Dataframe</h3>

#### Definition
DataFrame is like a worksheet in Excel:
- Two-dimensional labeled data structure.
- Created from dictionaries, lists of dictionaries, NumPy arrays.

#### Basic Syntax

```python
pd.DataFrame(data, columns=columns, index=index)
```
</div>

In [4]:
import pandas as pd
data = {'pears': [5, 7, 11, 13], 'oranges':[12, 2, 3, 5]}

#Pass this data to DataFrame constructor

df = pd.DataFrame(data)
df

   pears  oranges
0      5       12
1      7        2
2     11        3
3     13        5

<div style="background-color: #9DC9D5; padding: 10px;">

## Creating Custom Row Index
Each `(key, value)` item in the data corresponds to a column in the resulting DataFrame.

The index of this DataFrame is initialized by default as numbers (0, 1, 2, ...), but you can also create your own custom index when initializing the DataFrame.

In [5]:
data = {'pears': [5, 7, 11, 13], 'oranges':[12, 2, 3, 5]}

#Creating custom row index

fruits_df = pd.DataFrame(data, index = ['Sam','Jam', 'Tam', 'Dam'])
fruits_df

     pears  oranges
Sam      5       12
Jam      7        2
Tam     11        3
Dam     13        5

<div style="background-color: #9DC9D5; padding: 15px; border-radius: 5px;">

## Column Indexes

A **Column Index** identifies and accesses DataFrame columns, each uniquely labeled.

### Key Points:
- **Horizontal orientation**  
- Labels for identifying columns  
- Used to access specific data  

### Examples:
- Access a column: 
  ```python
  df['Column Label'] 
  ```
  ```python
  df.column_label
  ```
  ```python
  df[['column_label1', 'column_label2', 'columnlabel3']]
  ```

In [6]:
fruits_df['pears']
#fruits_df.pears

Sam     5
Jam     7
Tam    11
Dam    13
Name: pears, dtype: int64

In [7]:
fruits_df[['pears', 'oranges']]

     pears  oranges
Sam      5       12
Jam      7        2
Tam     11        3
Dam     13        5

<div style="background-color: #9DC9D5; padding: 15px; border-radius: 5px;">

## Row Indexes

A **Row Index** refers to the labels or integers that identify and access rows in a DataFrame.  
Rows are typically assigned an integer index by default, but this can be customized as needed.

### Key Points:
- **Vertical orientation**  
- Labels or integers are used to identify and access rows  
- Rows can have custom indices, but by default, they have integer indices  
- Used for selecting and filtering data observations  

### Examples:
- Access a specific row by label:  
  ```python
  df.loc['row_label']
  df.loc[['row_label1', 'row_label2']]
  ```
- Access a specific row by integer index:  
  ```python
  df.iloc[row_index]
  df.iloc[start_index:end_index]
  ```

In [8]:
fruits_df.loc['Sam']

pears       5
oranges    12
Name: Sam, dtype: int64

In [9]:
fruits_df.loc[['Jam', 'Tam']]

     pears  oranges
Jam      7        2
Tam     11        3

In [10]:
fruits_df.iloc[1]

pears      7
oranges    2
Name: Jam, dtype: int64

In [11]:
fruits_df.iloc[0:4]

     pears  oranges
Sam      5       12
Jam      7        2
Tam     11        3
Dam     13        5

In [12]:
fruits_df.iloc[1:3, [0,1]]

     pears  oranges
Jam      7        2
Tam     11        3

<div style="background-color: #9DC9D5; padding: 10px;">

## `pandas.DataFrame.from_dict`
This is a class method of the `pandas.DataFrame` class.

### Syntax:
```python
pandas.DataFrame.from_dict(data, orient='columns', dtype=None, columns=None)
```
    

This method allows flexibility in how the data is structured in the dictionary, providing control over how the DataFrame is created.

In [13]:
import pandas as pd
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data)
df

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [14]:
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data, orient='index')
df

       0  1  2  3
col_1  3  2  1  0
col_2  a  b  c  d

In [15]:
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data, orient='index',columns = ['A','B','C','D'])
df

       A  B  C  D
col_1  3  2  1  0
col_2  a  b  c  d

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">

## `pandas.read_csv`
The `read_csv` function in the `pandas` library allows you to easily load data from CSV files into a DataFrame.

### Syntax:
```python
pandas.read_csv(filepath_or_buffer, sep=',', index_col=None, dtype=None, ... )
```
CSVs don't have indexes like our DataFrames, so all we need to do is just designate the index_col. We are setting the index to be column zero.

In [16]:
#Reading data and viewing data from a CSV File
import pandas as pd

#Create a blank dataframe
imaging_df = pd.DataFrame()

#Load data from the CSV file
csv_file = "Files/MSD_Imaging.csv"
imaging_df = pd.read_csv(csv_file)
imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity
0,40985,37.0,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,9/24/2022,Standard X-ray,73030,X-ray exam of shoulder,63.40,1
1,55043,NaN,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,1/30/2023,Ultrasound,93306,Tte w/doppler complete,95.70,1
2,59784,NaN,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2/1/2023,Standard X-ray,73630,X-ray exam of foot,160.00,1
3,31182,43.0,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,4/29/2022,Standard X-ray,73560,X-ray exam of knee 1 or 2,63.40,1
4,15640,49.0,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,6/19/2022,Standard X-ray,73630,X-ray exam of foot,63.40,1
...,...,...,...,...,...,...,...,...,...,...,...,...
13180,22205,41.0,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,12/18/2022,Ultrasound,93971,Extremity study,691.60,1
13181,39950,64.0,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,1/10/2022,CT Scan,72125,Ct neck spine w/o dye,64.31,1
13182,35619,47.0,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,1/17/2022,Standard X-ray,73560,X-ray exam of knee 1 or 2,95.00,1
13183,39682,58.0,Low back pain,M545,Low back pain,Outpatient Hospital,8/21/2022,Standard X-ray,72114,X-ray exam l-s spine bending,146.41,1
13184,31303,61.0,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,12/28/2022,Standard X-ray,73110,X-ray exam of wrist,63.40,1

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">

## Verify the Data Load

### `df.head()`
The `df.head()` function displays the first few rows of the DataFrame. This is useful for quickly verifying the structure and content of the data after loading it. You can pass an optional parameter to specify the number of rows to display. For example: df.head(2)

### `df.tail()`   
The `df.tail()` displays the last few rows of the DataFrame to verify the data load.

In [17]:
imaging_df.head()

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity
0,40985,37.0,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,9/24/2022,Standard X-ray,73030,X-ray exam of shoulder,63.4,1
1,55043,NaN,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,1/30/2023,Ultrasound,93306,Tte w/doppler complete,95.7,1
2,59784,NaN,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2/1/2023,Standard X-ray,73630,X-ray exam of foot,160.0,1
3,31182,43.0,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,4/29/2022,Standard X-ray,73560,X-ray exam of knee 1 or 2,63.4,1
4,15640,49.0,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,6/19/2022,Standard X-ray,73630,X-ray exam of foot,63.4,1

In [18]:
imaging_df.tail(5)

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity
13180,22205,41.0,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,12/18/2022,Ultrasound,93971,Extremity study,691.60,1
13181,39950,64.0,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,1/10/2022,CT Scan,72125,Ct neck spine w/o dye,64.31,1
13182,35619,47.0,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,1/17/2022,Standard X-ray,73560,X-ray exam of knee 1 or 2,95.00,1
13183,39682,58.0,Low back pain,M545,Low back pain,Outpatient Hospital,8/21/2022,Standard X-ray,72114,X-ray exam l-s spine bending,146.41,1
13184,31303,61.0,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,12/28/2022,Standard X-ray,73110,X-ray exam of wrist,63.40,1

In [19]:
#View the data columns
imaging_df.columns

Index(['Person_Id', 'Person_Age', 'Diagnosis_Group', 'Diagnosis_Code',
       'Diagnosis_Description', 'Place_of_Service_Description', 'Service_Date',
       'Procedure_Group', 'Procedure_Code', 'Procedure_Description', 'Cost',
       'Quantity'],
      dtype='object')

In [20]:
#View the data index/rows
imaging_df.index

RangeIndex(start=0, stop=13185, step=1)

In [21]:
#Accessing a series(column)
imaging_df.Person_Age

0        37.0
1         NaN
2         NaN
3        43.0
4        49.0
         ...
13180    41.0
13181    64.0
13182    47.0
13183    58.0
13184    61.0
Name: Person_Age, Length: 13185, dtype: float64

In [22]:
#Accessing multiple columns
imaging_df[['Person_Age','Diagnosis_Group','Procedure_Description']]

,Person_Age,Diagnosis_Group,Procedure_Description
0,37.0,"Musculoskeletal pain, not low back pain",X-ray exam of shoulder
1,NaN,Systemic lupus erythematosus and connective ti...,Tte w/doppler complete
2,NaN,"Musculoskeletal pain, not low back pain",X-ray exam of foot
3,43.0,"Musculoskeletal pain, not low back pain",X-ray exam of knee 1 or 2
4,49.0,"Musculoskeletal pain, not low back pain",X-ray exam of foot
...,...,...,...
13180,41.0,"Musculoskeletal pain, not low back pain",Extremity study
13181,64.0,Spondylopathies/spondyloarthropathy (including...,Ct neck spine w/o dye
13182,47.0,Other specified joint disorders,X-ray exam of knee 1 or 2
13183,58.0,Low back pain,X-ray exam l-s spine bending
13184,61.0,"Musculoskeletal pain, not low back pain",X-ray exam of wrist

In [23]:
#Using df.loc[] to select by name
imaging_df.loc[1300:1310]

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity
1300,7871,NaN,"Musculoskeletal pain, not low back pain",M79644,Pain in right finger(s),Office,1/31/2023,Standard X-ray,73140,X-ray exam of finger(s),42.23,1
1301,60952,36.0,Other specified connective tissue disease,M722,Plantar fascial fibromatosis,Outpatient Hospital,9/29/2022,Standard X-ray,73630,X-ray exam of foot,63.40,1
1302,4207,NaN,"Musculoskeletal pain, not low back pain",M25512,Pain in left shoulder,Outpatient Hospital,4/7/2023,Standard X-ray,73030,X-ray exam of shoulder,160.00,1
1303,17995,NaN,Low back pain,M545,Low back pain,Outpatient Hospital,11/6/2022,Standard X-ray,62290,Njx px discography lumbar,175.48,1
1304,19681,34.0,Spondylopathies/spondyloarthropathy (including...,M4802,"Spinal stenosis, cervical region",Outpatient Hospital,3/18/2022,MR,72148,Mri lumbar spine w/o dye,380.00,1
1305,50347,32.0,Spondylopathies/spondyloarthropathy (including...,M48061,"Spinal stenosis, lumbar region without neuroge...",Outpatient Hospital,4/5/2023,MR,72148,Mri lumbar spine w/o dye,740.00,1
1306,3188,64.0,Osteoarthritis,M19032,"Primary osteoarthritis, left wrist",Outpatient Hospital,8/7/2022,Standard X-ray,73110,X-ray exam of wrist,63.40,1
1307,56326,53.0,"Musculoskeletal pain, not low back pain",M25512,Pain in left shoulder,Office,1/11/2023,Standard X-ray,73030,X-ray exam of shoulder,42.67,1
1308,39902,54.0,Acquired deformities (excluding foot),M24571,"Contracture, right ankle",Office,9/1/2022,Ultrasound,76882,Us lmtd jt/fcl evl nvasc xtr,64.73,1
1309,59045,33.0,"Musculoskeletal pain, not low back pain",M25512,Pain in left shoulder,Office,12/28/2022,Standard X-ray,73030,X-ray exam of shoulder,42.67,1
1310,56161,60.0,Spondylopathies/spondyloarthropathy (including...,M48061,"Spinal stenosis, lumbar region without neuroge...",Outpatient Hospital,12/17/2022,Standard X-ray,73502,X-ray exam hip uni 2-3 views,63.40,1

In [24]:
#Using df.iloc[] to select rows and columns by their position
imaging_df.loc[1300:1310,['Procedure_Description', 'Person_Age']]

             Procedure_Description  Person_Age
1300       X-ray exam of finger(s)         NaN
1301            X-ray exam of foot        36.0
1302        X-ray exam of shoulder         NaN
1303     Njx px discography lumbar         NaN
1304      Mri lumbar spine w/o dye        34.0
1305      Mri lumbar spine w/o dye        32.0
1306           X-ray exam of wrist        64.0
1307        X-ray exam of shoulder        53.0
1308  Us lmtd jt/fcl evl nvasc xtr        54.0
1309        X-ray exam of shoulder        33.0
1310  X-ray exam hip uni 2-3 views        60.0

In [25]:
imaging_df.iloc[1300:1310,[1,3]]

      Person_Age Diagnosis_Code
1300         NaN         M79644
1301        36.0           M722
1302         NaN         M25512
1303         NaN           M545
1304        34.0          M4802
1305        32.0         M48061
1306        64.0         M19032
1307        53.0         M25512
1308        54.0         M24571
1309        33.0         M25512

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">

## Data Inspection Commands
The following commands are essential for inspecting and understanding the structure of your `pandas` DataFrame.

### `df.info()`
The `df.info()` Provides essential details about your dataset.
- Number of rows and columns.
- Number of non-null values.
- Data type of each column.
- Memory usage of the DataFrame.


### `df.shape`
The `df.shape` returns the number of rows and columns in the DataFrame as a tuple (rows, columns).

### `df.dtypes`
The `df.dtypes` displays the data type of each column in the DataFrame.
 
### `df.describe()`
The `df.describe()` provides statistical summary for numerical columns (e.g., mean, median, standard deviation, etc.).
    
### `df.describe(include='all')`
The `df.describe(include='all')` includes a summary of all columns, including categorical ones, if present.

In [26]:
imaging_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13185 entries, 0 to 13184
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Person_Id                     13185 non-null  int64
 1   Person_Age                    11614 non-null  float64
 2   Diagnosis_Group               13185 non-null  object
 3   Diagnosis_Code                13185 non-null  object
 4   Diagnosis_Description         13185 non-null  object
 5   Place_of_Service_Description  13185 non-null  object
 6   Service_Date                  13185 non-null  object
 7   Procedure_Group               13185 non-null  object
 8   Procedure_Code                13185 non-null  object
 9   Procedure_Description         13184 non-null  object
 10  Cost                          13185 non-null  float64
 11  Quantity                      13185 non-null  int64
dtypes: float64(2), int64(2), object(8)
memory usage: 1.2+ MB

In [27]:
imaging_df.shape

(13185, 12)

In [28]:
imaging_df.dtypes

Person_Id                         int64
Person_Age                      float64
Diagnosis_Group                  object
Diagnosis_Code                   object
Diagnosis_Description            object
Place_of_Service_Description     object
Service_Date                     object
Procedure_Group                  object
Procedure_Code                   object
Procedure_Description            object
Cost                            float64
Quantity                          int64
dtype: object

In [29]:
imaging_df.describe()

          Person_Id    Person_Age          Cost      Quantity
count  13185.000000  11614.000000  13185.000000  13185.000000
mean   31468.458172     49.042621    195.137718      1.986196
std    17933.507049     12.774478    266.669665      9.762903
min        5.000000     21.000000     40.000000      1.000000
25%    16577.000000     40.000000     63.400000      1.000000
50%    31286.000000     51.000000     97.730000      1.000000
75%    47148.000000     60.000000    171.000000      1.000000
max    62109.000000     85.000000   2998.950000    225.000000

In [30]:
imaging_df.describe(include = 'all')

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity
count,13185.000000,11614.000000,13185,13185,13185,13185,13185,13185,13185,13184,13185.000000,13185.000000
unique,NaN,NaN,32,666,666,11,474,6,214,201,NaN,NaN
top,NaN,NaN,"Musculoskeletal pain, not low back pain",M545,Low back pain,Outpatient Hospital,10/14/2022,Standard X-ray,72148,Mri lumbar spine w/o dye,NaN,NaN
freq,NaN,NaN,4071,525,525,8530,74,7997,886,886,NaN,NaN
mean,31468.458172,49.042621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195.137718,1.986196
std,17933.507049,12.774478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,266.669665,9.762903
min,5.000000,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,1.000000
25%,16577.000000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.400000,1.000000
50%,31286.000000,51.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.730000,1.000000
75%,47148.000000,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171.000000,1.000000
max,62109.000000,85.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2998.950000,225.000000

In [31]:
#Get the row count only
print(imaging_df.shape)
print(imaging_df.shape[0])

(13185, 12)
13185

In [32]:
#Get control totals for cost and quantity

total_cost = imaging_df['Cost'].sum()
total_quantity = imaging_df['Quantity'].sum()
print(f"Total Cost: {total_cost}")
print(f"Total Quantity: {total_quantity}")

Total Cost: 2572890.81
Total Quantity: 26188

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Check for missing  values in a dataframe.
### `df.isnull().sum()`
</div>

In [33]:
imaging_df.isnull().sum() #We can notice that Person_Age has 1571 null values

Person_Id                          0
Person_Age                      1571
Diagnosis_Group                    0
Diagnosis_Code                     0
Diagnosis_Description              0
Place_of_Service_Description       0
Service_Date                       0
Procedure_Group                    0
Procedure_Code                     0
Procedure_Description              1
Cost                               0
Quantity                           0
dtype: int64

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Fix the missing  values in a dataframe.
### `df['Column_Name'].fillna(value, inplace=False).astype(dtype)`
    
Key points:
 - Use .fillna() to handle missing values effectively.
 - Set inplace=True to update the DataFrame directly or leave it as False to create a new DataFrame.
 - Always ensure the replacement value (value) is compatible with the desired data type (dtype).
</div>

In [34]:
#Fill the empty values for Person_Age with default_age as 0.0 and set the datatype to float
default_age = 0.0
imaging_df['Person_Age'] = imaging_df['Person_Age'].fillna(default_age).astype(float)
imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity
0,40985,37.0,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,9/24/2022,Standard X-ray,73030,X-ray exam of shoulder,63.40,1
1,55043,0.0,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,1/30/2023,Ultrasound,93306,Tte w/doppler complete,95.70,1
2,59784,0.0,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2/1/2023,Standard X-ray,73630,X-ray exam of foot,160.00,1
3,31182,43.0,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,4/29/2022,Standard X-ray,73560,X-ray exam of knee 1 or 2,63.40,1
4,15640,49.0,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,6/19/2022,Standard X-ray,73630,X-ray exam of foot,63.40,1
...,...,...,...,...,...,...,...,...,...,...,...,...
13180,22205,41.0,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,12/18/2022,Ultrasound,93971,Extremity study,691.60,1
13181,39950,64.0,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,1/10/2022,CT Scan,72125,Ct neck spine w/o dye,64.31,1
13182,35619,47.0,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,1/17/2022,Standard X-ray,73560,X-ray exam of knee 1 or 2,95.00,1
13183,39682,58.0,Low back pain,M545,Low back pain,Outpatient Hospital,8/21/2022,Standard X-ray,72114,X-ray exam l-s spine bending,146.41,1
13184,31303,61.0,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,12/28/2022,Standard X-ray,73110,X-ray exam of wrist,63.40,1

In [35]:
#Verify if the Person_Age has null values
imaging_df.isnull().sum()

Person_Id                       0
Person_Age                      0
Diagnosis_Group                 0
Diagnosis_Code                  0
Diagnosis_Description           0
Place_of_Service_Description    0
Service_Date                    0
Procedure_Group                 0
Procedure_Code                  0
Procedure_Description           1
Cost                            0
Quantity                        0
dtype: int64

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Convert any fields that are imported incorrectly
Convert strings to pandas datetime objects for easier analysis.
### `pd.to_datetime(df['Column_Name'], format=None, errors='raise', infer_datetime_format=False)`

    
Key points:
 - Column: Specify the column with df['Column_Name'].
 - Format: Use format='%Y-%m-%d' for consistent date formats.
 - Error Handling:
     - 'raise': Default, raises errors.
     - 'coerce': Converts invalid values to NaT.
     - 'ignore': Leaves values unchanged on errors.
 - Inference: Use infer_datetime_format=True for automatic format detection.

</div>

In [36]:
# Convert 'Service_Date' column from object to datetime data type
imaging_df['Service_Date'] = pd.to_datetime(imaging_df['Service_Date'])
imaging_df.dtypes

Person_Id                                int64
Person_Age                             float64
Diagnosis_Group                         object
Diagnosis_Code                          object
Diagnosis_Description                   object
Place_of_Service_Description            object
Service_Date                    datetime64[ns]
Procedure_Group                         object
Procedure_Code                          object
Procedure_Description                   object
Cost                                   float64
Quantity                                 int64
dtype: object

In [37]:
imaging_df.describe() #By converting Service_Date column to DateTime datatype, the summary statistics are available

,Person_Id,Person_Age,Service_Date,Cost,Quantity
count,13185.000000,13185.000000,13185,13185.000000,13185.000000
mean,31468.458172,43.199166,2022-09-17 13:00:20.477815808,195.137718,1.986196
min,5.000000,0.000000,2022-01-01 00:00:00,40.000000,1.000000
25%,16577.000000,33.000000,2022-06-08 00:00:00,63.400000,1.000000
50%,31286.000000,48.000000,2022-09-29 00:00:00,97.730000,1.000000
75%,47148.000000,58.000000,2023-01-15 00:00:00,171.000000,1.000000
max,62109.000000,85.000000,2023-04-30 00:00:00,2998.950000,225.000000
std,17933.507049,19.904610,NaN,266.669665,9.762903

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Binning or Bucketing 
Creating new fields for reporting uses (Bucket Dates)
### `df['Column_Name'].dt.to_period(freq)`

    
Key points:
 - to_period(freq) = converts the datetime-like values into Period objects with the specified frequency (freq).
     - 'D': Daily frequency, representing a single day.
     - 'M': Monthly frequency, representing a single month.
     - 'Q': Quarterly frequency, representing a single quarter.
     - 'Y': Yearly frequency, representing a single year.
</div>

In [38]:
#Create the 'Year_Qtr' column by formatting 'Service_Date' as qtr periods
imaging_df['Year_Qtr'] = imaging_df['Service_Date'].dt.to_period('Q')
imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr
0,40985,37.0,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,2022-09-24,Standard X-ray,73030,X-ray exam of shoulder,63.40,1,2022Q3
1,55043,0.0,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,2023-01-30,Ultrasound,93306,Tte w/doppler complete,95.70,1,2023Q1
2,59784,0.0,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2023-02-01,Standard X-ray,73630,X-ray exam of foot,160.00,1,2023Q1
3,31182,43.0,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,2022-04-29,Standard X-ray,73560,X-ray exam of knee 1 or 2,63.40,1,2022Q2
4,15640,49.0,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,2022-06-19,Standard X-ray,73630,X-ray exam of foot,63.40,1,2022Q2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13180,22205,41.0,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,2022-12-18,Ultrasound,93971,Extremity study,691.60,1,2022Q4
13181,39950,64.0,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,2022-01-10,CT Scan,72125,Ct neck spine w/o dye,64.31,1,2022Q1
13182,35619,47.0,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,2022-01-17,Standard X-ray,73560,X-ray exam of knee 1 or 2,95.00,1,2022Q1
13183,39682,58.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-08-21,Standard X-ray,72114,X-ray exam l-s spine bending,146.41,1,2022Q3
13184,31303,61.0,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,2022-12-28,Standard X-ray,73110,X-ray exam of wrist,63.40,1,2022Q4

In [39]:
# Create the new 'Service_Month' column
imaging_df['Service_Month'] = imaging_df['Service_Date'].dt.month
imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month
0,40985,37.0,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,2022-09-24,Standard X-ray,73030,X-ray exam of shoulder,63.40,1,2022Q3,9
1,55043,0.0,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,2023-01-30,Ultrasound,93306,Tte w/doppler complete,95.70,1,2023Q1,1
2,59784,0.0,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2023-02-01,Standard X-ray,73630,X-ray exam of foot,160.00,1,2023Q1,2
3,31182,43.0,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,2022-04-29,Standard X-ray,73560,X-ray exam of knee 1 or 2,63.40,1,2022Q2,4
4,15640,49.0,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,2022-06-19,Standard X-ray,73630,X-ray exam of foot,63.40,1,2022Q2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13180,22205,41.0,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,2022-12-18,Ultrasound,93971,Extremity study,691.60,1,2022Q4,12
13181,39950,64.0,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,2022-01-10,CT Scan,72125,Ct neck spine w/o dye,64.31,1,2022Q1,1
13182,35619,47.0,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,2022-01-17,Standard X-ray,73560,X-ray exam of knee 1 or 2,95.00,1,2022Q1,1
13183,39682,58.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-08-21,Standard X-ray,72114,X-ray exam l-s spine bending,146.41,1,2022Q3,8
13184,31303,61.0,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,2022-12-28,Standard X-ray,73110,X-ray exam of wrist,63.40,1,2022Q4,12

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Creating bin edges and bin labels using pd.cut() 
pd.cut() is a Pandas function that segments and categorizes continuous or numeric data into discrete bins or intervals

### `pd.cut(x, bins, labels=None, right=True)`

    
Key points:
 - x : The input array or pandas Series to be binned.
 - bins:
    - Specifies the bins for binning the data.
    - Can be an integer (number of equal-width bins) or an array specifying the bin edges.
 - labels (default: None):
    - Specifies the labels for the bins.
    - If False, returns the bin intervals instead of labels.
 - right (default: True):
    - Whether the intervals are closed on the right.
    - True: Bins include the right edge, e.g., (a, b].
    - False: Bins include the left edge, e.g., [a, b).

</div>

In [40]:
# Define the bin edges for the specified groups
bin_edges = [-1, 0, 20, 30, 40, 50, 60, 70, 80, 100]

# Define labels for each group
bin_labels = ['NA', '0-20', '21-30', '31-40', '41-50', '51-60','61-70', '71-80','81 plus']

imaging_df['Person_Age_Group'] = pd.cut(imaging_df['Person_Age'], bins = bin_edges, labels = bin_labels)
imaging_df[['Person_Age','Person_Age_Group']].head(5)

   Person_Age Person_Age_Group
0        37.0            31-40
1         0.0               NA
2         0.0               NA
3        43.0            41-50
4        49.0            41-50

In [41]:
bin_edges = [0, 100, 250, 500, 1000, float('inf')]
#The float('inf') represents positive infinity in Python

bin_labels = ['0 to 100', '101 to 250', '251 to 500', '501 to 1000', '1000 plus']

imaging_df['Cost_Buckets'] = pd.cut(imaging_df['Cost'], bins = bin_edges, labels = bin_labels, right=False)
imaging_df[['Cost','Cost_Buckets']].head(5)

    Cost Cost_Buckets
0   63.4     0 to 100
1   95.7     0 to 100
2  160.0   101 to 250
3   63.4     0 to 100
4   63.4     0 to 100

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Create new fields using Lambda functions 
They are small, anonymous functions can receive multiple arguments, but can only contain one expression (the return value)

### `df['Existing_Column'].apply(lambda x: value_if_condition if condition else value_if_else)`

    
Key points:
 - df['Existing_Column'] : Specifies the column to which the transformation will be applied.
 - lambda x: Defines an inline anonymous function where x represents each value in the column.
 - condition: The condition to evaluate for each value in the column.
 - value_if_condition: The value to assign if the condition is True.
 - value_if_else: The value to assign if the condition is False.
</div>

In [42]:
imaging_df['X_Ray_Grouper'] = imaging_df['Procedure_Group'].apply(lambda x: 'X Ray' if x=='Standard X-ray' else 'Other')
imaging_df[['Procedure_Group','X_Ray_Grouper']].head(5)

  Procedure_Group X_Ray_Grouper
0  Standard X-ray         X Ray
1      Ultrasound         Other
2  Standard X-ray         X Ray
3  Standard X-ray         X Ray
4  Standard X-ray         X Ray

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Aggregate functions for groupby method
Aggregation functions in pandas' groupby method are used to summarize or perform calculations on grouped data. These functions operate on numeric, categorical, or datetime data to derive meaningful insights.

### `df.groupby(by, axis=0)[agg_column].agg(func)`
   
Key points:
 - df.groupby(): Groups the data based on specified criteria.
 - Parameters:
     - by: Column(s) or array(s) to group by. Example: 'Column_Name' or ['Col1', 'Col2'].
     - axis (default: 0): Group along rows (0) or columns (1).
 - [agg_column]: Use [agg_column] to specify the column to apply the aggregation function.
 - agg(func): Applies an aggregation function (sum, mean, count, etc.) to the grouped data.
</div>

In [43]:
#()- This is the column you want to group by. In your DataFrame, it might be something like: Diagnosis_Group
#[] - This is the column whose values you want to sum. In your DataFrame, it could be a numerical column, such as: Cost, Person_Age
sum_values = imaging_df.groupby('Procedure_Group')['Cost'].sum()

mean_values = imaging_df.groupby('Procedure_Group')['Cost'].mean()

median_values = imaging_df.groupby('Procedure_Group')['Cost'].median()

min_values = imaging_df.groupby('Procedure_Group')['Cost'].min()

max_values = imaging_df.groupby('Procedure_Group')['Cost'].max()

count_values =imaging_df.groupby('Procedure_Group')['Cost'].count()

std_values = imaging_df.groupby('Procedure_Group')['Cost'].std()

var_values = imaging_df.groupby('Procedure_Group')['Cost'].var()

data = {'sum' : sum_values, 'mean': mean_values, 'median': median_values, 'min':min_values, 'max':max_values, 'count':count_values}

agg_df = pd.DataFrame(data)
agg_df

,sum,mean,median,min,max,count
Procedure_Group,,,,,,
CT Scan,235572.99,281.449211,132.980,44.72,2156.96,837
Imaging - Miscellaneous,849.50,49.970588,46.660,42.01,92.74,17
MR,1202141.01,346.139076,227.530,40.54,2988.00,3473
Nuclear,43840.28,254.885349,82.875,41.80,1689.27,172
Standard X-ray,908432.51,113.596662,76.050,40.00,2933.70,7997
Ultrasound,182054.52,264.230073,88.130,41.34,2998.95,689

In [44]:
values = imaging_df.groupby('Procedure_Group')['Cost'].agg(['sum', 'mean', 'min'])
values

                                sum        mean    min
Procedure_Group
CT Scan                   235572.99  281.449211  44.72
Imaging - Miscellaneous      849.50   49.970588  42.01
MR                       1202141.01  346.139076  40.54
Nuclear                    43840.28  254.885349  41.80
Standard X-ray            908432.51  113.596662  40.00
Ultrasound                182054.52  264.230073  41.34

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Aggregate functions applied on a particular column DataFrame

</div>

In [45]:
imaging_df.Cost.sum()

2572890.81

In [46]:
imaging_df.Cost.mean()

195.1377178612059

In [47]:
imaging_df['Cost'].quantile([0.01, 0.05, 0.5, 0.95, 0.99])

0.01      40.5000
0.05      42.9000
0.50      97.7300
0.95     740.0000
0.99    1239.9768
Name: Cost, dtype: float64

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Counting Unique Values in a Column Using .nunique()

### `df['Column_Name'].nunique(dropna=True)`
   
Key points:
 - df['Column_Name']: Specifies the column in the DataFrame for which you want to count unique values.
 - .nunique(): Returns the number of unique values in the column.
 - dropna (default: True): 
    - If True, excludes NaN values from the count.
    - If False, includes NaN as a unique value.

</div>

In [48]:
#Get a unique count of value for a particular field/series
imaging_df['Procedure_Group'].nunique()

6

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Finding Unique Values in a Column Using .unique()

### `df['Column_Name'].unique()`
   
Key points:
 - The output is a NumPy array containing distinct elements in the column.
 - NaN values are included as a unique element if they exist in the column.
 - Useful for inspecting unique values in categorical or discrete datasets.

</div>

In [49]:
#Get a unique list of values for a particular field/series
imaging_df['Procedure_Group'].unique()

array(['Standard X-ray', 'Ultrasound', 'MR', 'CT Scan', 'Nuclear',
       'Imaging - Miscellaneous'], dtype=object)

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Summarizing Data Frequency with .value_counts()
The .value_counts() function in pandas is used to compute the frequency of unique values in a column or Series. It is highly effective for summarizing categorical or discrete data.
    
### `df['Column_Name'].value_counts(normalize=False, sort=True, ascending=False)`
   
Key points:
 - Parameters:
     - normalize: Return relative frequencies if True. (To see results as percentages)
     - sort: Sort counts in descending order (True) or retain the original order (False).
     - ascending: Sort counts in ascending order if True.

</div>

In [50]:
# value_counts() represents the count of unique values in a specified column of a DataFrame or a Series. It is commonly used to determine the frequency of each unique value within a column.
imaging_df['Procedure_Group'].value_counts()

Procedure_Group
Standard X-ray             7997
MR                         3473
CT Scan                     837
Ultrasound                  689
Nuclear                     172
Imaging - Miscellaneous      17
Name: count, dtype: int64

In [51]:
#Pass in normalize=True to see this result as percentages
imaging_df['Procedure_Group'].value_counts(normalize=True)

Procedure_Group
Standard X-ray             0.606523
MR                         0.263405
CT Scan                    0.063481
Ultrasound                 0.052256
Nuclear                    0.013045
Imaging - Miscellaneous    0.001289
Name: proportion, dtype: float64

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Filtering Dataframe - Boolean mask or query() method

</div>

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Filtering Dataframe - Boolean mask method
It's a way to specify which rows/columns we want to select ( True ) and which we don't ( False ). We surround each condition with parentheses, and we use bitwise operators ( & , | , ~ ) instead of logical operators ( and , or , not ).
    
### `(df['Column_Name1'] condition1) & (df['Column_Name2'] condition2)`
   
Key points:
 - Parameters:
     - df['Column_Name1'] condition1: Applies the first condition to a specific column. Example: df['Column_Name1'] > value
     - &: Logical AND operator. Combines multiple conditions. Use | for OR.
     - df['Column_Name2'] condition2: Applies the second condition to another column. Example: df['Column_Name2'] == 'value'
     - Parentheses (): Group each condition in parentheses to ensure proper precedence.
</div>

In [52]:
#Boolean mask to filter the imaging records for people with lower back pain that had a cost greater than $50 
(imaging_df['Cost'] > 50) & (imaging_df.Diagnosis_Group == 'Low back pain')

0        False
1        False
2        False
3        False
4        False
         ...
13180    False
13181    False
13182    False
13183     True
13184    False
Length: 13185, dtype: bool

In [53]:
#Boolean mask to select the subset of imaging records costing more than $1200 and are for Magnetic Resonance (MR).
imaging_df[(imaging_df['Cost'] > 1200) & (imaging_df.Procedure_Group == 'MR')]

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
497,19428,26.0,Other specified joint disorders,M2391,Unspecified internal derangement of right knee,Outpatient Hospital,2022-08-03,MR,73721,Mri jnt of lwr extre w/o dye,2452.00,1,2022Q3,8,21-30,1000 plus,Other
534,42274,48.0,Spondylopathies/spondyloarthropathy (including...,M5126,"Other intervertebral disc displacement, lumbar...",Outpatient Hospital,2023-02-11,MR,72148,Mri lumbar spine w/o dye,2832.30,1,2023Q1,2,41-50,1000 plus,Other
793,39863,38.0,Other specified joint disorders,M2241,"Chondromalacia patellae, right knee",Outpatient Hospital,2022-05-27,MR,73721,Mri jnt of lwr extre w/o dye,2254.42,1,2022Q2,5,31-40,1000 plus,Other
830,31678,30.0,Other specified connective tissue disease,M7581,"Other shoulder lesions, right shoulder",Outpatient Hospital,2022-03-19,MR,73221,Mri joint upr extrem w/o dye,2209.45,1,2022Q1,3,21-30,1000 plus,Other
969,6740,41.0,Spondylopathies/spondyloarthropathy (including...,M50222,Other cervical disc displacement at C5-C6 level,Outpatient Hospital,2022-02-26,MR,70553,Mri brain stem w/o & w/dye,2198.00,2,2022Q1,2,41-50,1000 plus,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12015,6695,60.0,Spondylopathies/spondyloarthropathy (including...,M5126,"Other intervertebral disc displacement, lumbar...",Outpatient Hospital,2022-08-04,MR,72148,Mri lumbar spine w/o dye,2349.60,1,2022Q3,8,51-60,1000 plus,Other
12086,11534,0.0,"Musculoskeletal pain, not low back pain",M25562,Pain in left knee,Outpatient Hospital,2023-01-19,MR,73721,Mri jnt of lwr extre w/o dye,1567.48,1,2023Q1,1,NA,1000 plus,Other
12232,37597,0.0,Spondylopathies/spondyloarthropathy (including...,M4306,"Spondylolysis, lumbar region",Office,2022-12-05,MR,72148,Mri lumbar spine w/o dye,1900.00,2,2022Q4,12,NA,1000 plus,Other
12691,32297,25.0,Low back pain,M545,Low back pain,Outpatient Hospital,2023-02-08,MR,72148,Mri lumbar spine w/o dye,2758.28,1,2023Q1,2,21-30,1000 plus,Other
13169,4402,25.0,Other specified bone disease and musculoskelet...,M93262,"Osteochondritis dissecans, left knee",Outpatient Hospital,2022-08-06,MR,73721,Mri jnt of lwr extre w/o dye,2254.42,1,2022Q3,8,21-30,1000 plus,Other

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Filtering Dataframe - query() method
It's a way to specify which rows/columns we want to select ( True ) and which we don't ( False ). We surround each condition with parentheses, and we  can use bitwise operators ( & , | , ~ ) and logical operators ( and , or , not ).
    
### `df.query("condition1 and/or condition2")`
   
Key points:
 - Parameters:
     - df.query(): Allows querying the DataFrame using a string expression for filtering rows.
     - "condition1 and/or condition2": Write conditions as a string, similar to SQL syntax. Use and for logical AND.
     - Referencing Columns: 
        - Column names are directly referenced in the string without df['Column_Name'].
        - For column names with spaces or special characters, use backticks (`Column Name`).
</div>

In [54]:
imaging_df.query("Cost>250 and Diagnosis_Group=='Low back pain'")

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
11,50366,24.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-12-04,MR,72148,Mri lumbar spine w/o dye,1017.85,1,2022Q4,12,21-30,1000 plus,Other
326,34200,49.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-10-30,CT Scan,74176,Ct abd & pelvis w/o contrast,522.90,1,2022Q4,10,41-50,501 to 1000,Other
463,22485,0.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-12-23,MR,72148,Mri lumbar spine w/o dye,380.00,1,2022Q4,12,NA,251 to 500,Other
742,48480,35.0,Low back pain,M545,Low back pain,Outpatient Hospital,2023-02-22,Standard X-ray,72110,X-ray exam l-2 spine 4/>vws,309.40,1,2023Q1,2,31-40,251 to 500,X Ray
870,13501,51.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-09-14,Standard X-ray,72100,X-ray exam l-s spine 2/3 vws,323.35,1,2022Q3,9,51-60,251 to 500,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12691,32297,25.0,Low back pain,M545,Low back pain,Outpatient Hospital,2023-02-08,MR,72148,Mri lumbar spine w/o dye,2758.28,1,2023Q1,2,21-30,1000 plus,Other
12809,51920,65.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-07-07,Standard X-ray,71046,X-ray exam chest 2 views,417.77,1,2022Q3,7,61-70,251 to 500,X Ray
12927,2487,44.0,Low back pain,M545,Low back pain,Office,2022-09-08,MR,72148,Mri lumbar spine w/o dye,265.47,1,2022Q3,9,41-50,251 to 500,Other
12966,5370,42.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-08-09,MR,72148,Mri lumbar spine w/o dye,380.00,1,2022Q3,8,41-50,251 to 500,Other
12970,19898,0.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-07-23,Standard X-ray,72110,X-ray exam l-2 spine 4/>vws,679.22,1,2022Q3,7,NA,501 to 1000,X Ray

In [55]:
#Filter dataframe using query() method looking at between two ranges:
imaging_df.query("'1/1/2023'<=Service_Date<='1/31/2023'and Person_Age>=65")

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
49,20405,74.0,Osteoporosis,M810,Age-related osteoporosis without current patho...,Outpatient Hospital,2023-01-29,Standard X-ray,77080,Dxa bone density axial,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
177,27746,67.0,"Musculoskeletal pain, not low back pain",M25551,Pain in right hip,Office,2023-01-18,Standard X-ray,73502,X-ray exam hip uni 2-3 views,51.35,1,2023Q1,1,61-70,0 to 100,X Ray
232,42352,69.0,Osteoarthritis,M1611,"Unilateral primary osteoarthritis, right hip",Outpatient Hospital,2023-01-13,Standard X-ray,73502,X-ray exam hip uni 2-3 views,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
240,29463,65.0,Other specified joint disorders,M23322,"Other meniscus derangements, posterior horn of...",Off Campus-Outpatient Hospital,2023-01-21,MR,73721,Mri jnt of lwr extre w/o dye,75.79,1,2023Q1,1,61-70,0 to 100,Other
540,20997,65.0,Other specified bone disease and musculoskelet...,M8589,Other specified disorders of bone density and ...,Outpatient Hospital,2023-01-22,Standard X-ray,77080,Dxa bone density axial,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12821,54418,67.0,Spondylopathies/spondyloarthropathy (including...,M5116,Intervertebral disc disorders with radiculopat...,Outpatient Hospital,2023-01-07,Standard X-ray,72100,X-ray exam l-s spine 2/3 vws,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
12835,25103,65.0,"Musculoskeletal pain, not low back pain",M25562,Pain in left knee,Office,2023-01-27,Standard X-ray,73564,X-ray exam knee 4 or more,55.32,1,2023Q1,1,61-70,0 to 100,X Ray
12948,22665,65.0,Other specified connective tissue disease,M7732,"Calcaneal spur, left foot",Outpatient Hospital,2023-01-22,Standard X-ray,73610,X-ray exam of ankle,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
13032,17559,65.0,Osteoarthritis,M19011,"Primary osteoarthritis, right shoulder",Outpatient Hospital,2023-01-07,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
13060,32591,73.0,Spondylopathies/spondyloarthropathy (including...,M4646,"Discitis, unspecified, lumbar region",Outpatient Hospital,2023-01-13,Nuclear,78803,Rp loclzj tum spect 1 area,1689.27,1,2023Q1,1,71-80,1000 plus,Other

In [56]:
filtered_imaging_df = pd.DataFrame()

filtered_imaging_df = imaging_df.query("'1/1/2023'<=Service_Date<='1/31/2023'and Person_Age>=65")
filtered_imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
49,20405,74.0,Osteoporosis,M810,Age-related osteoporosis without current patho...,Outpatient Hospital,2023-01-29,Standard X-ray,77080,Dxa bone density axial,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
177,27746,67.0,"Musculoskeletal pain, not low back pain",M25551,Pain in right hip,Office,2023-01-18,Standard X-ray,73502,X-ray exam hip uni 2-3 views,51.35,1,2023Q1,1,61-70,0 to 100,X Ray
232,42352,69.0,Osteoarthritis,M1611,"Unilateral primary osteoarthritis, right hip",Outpatient Hospital,2023-01-13,Standard X-ray,73502,X-ray exam hip uni 2-3 views,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
240,29463,65.0,Other specified joint disorders,M23322,"Other meniscus derangements, posterior horn of...",Off Campus-Outpatient Hospital,2023-01-21,MR,73721,Mri jnt of lwr extre w/o dye,75.79,1,2023Q1,1,61-70,0 to 100,Other
540,20997,65.0,Other specified bone disease and musculoskelet...,M8589,Other specified disorders of bone density and ...,Outpatient Hospital,2023-01-22,Standard X-ray,77080,Dxa bone density axial,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12821,54418,67.0,Spondylopathies/spondyloarthropathy (including...,M5116,Intervertebral disc disorders with radiculopat...,Outpatient Hospital,2023-01-07,Standard X-ray,72100,X-ray exam l-s spine 2/3 vws,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
12835,25103,65.0,"Musculoskeletal pain, not low back pain",M25562,Pain in left knee,Office,2023-01-27,Standard X-ray,73564,X-ray exam knee 4 or more,55.32,1,2023Q1,1,61-70,0 to 100,X Ray
12948,22665,65.0,Other specified connective tissue disease,M7732,"Calcaneal spur, left foot",Outpatient Hospital,2023-01-22,Standard X-ray,73610,X-ray exam of ankle,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
13032,17559,65.0,Osteoarthritis,M19011,"Primary osteoarthritis, right shoulder",Outpatient Hospital,2023-01-07,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
13060,32591,73.0,Spondylopathies/spondyloarthropathy (including...,M4646,"Discitis, unspecified, lumbar region",Outpatient Hospital,2023-01-13,Nuclear,78803,Rp loclzj tum spect 1 area,1689.27,1,2023Q1,1,71-80,1000 plus,Other

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Sorting DataFrame
The .sort_values() function in pandas is used to sort a DataFrame or Series by one or more columns or index values. It is a versatile and powerful method for ordering data in ascending or descending order. (ascending order by default)
    
### `df.sort_values(by, axis=0, ascending=True)`
   
Key points:
 - Parameters:
    - by: 
        - Column(s) to sort by. 
        - Can be a single column name (string) or a list of column names. 
        - Example: by='Column_Name' or by=['Column1', 'Column2'].
    - axis (default: 0):
        - Specifies whether to sort rows (0) or columns (1).
    - ascending (default: True):
        - Sorting order:
            - True: Ascending order.
            - False: Descending order.
        - For multiple columns, pass a list: ascending=[True, False].
</div>

In [57]:
filtered_imaging_df = filtered_imaging_df.sort_values(by=['Person_Age', 'Service_Date'])
filtered_imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
1405,27279,65.0,Spondylopathies/spondyloarthropathy (including...,M4807,"Spinal stenosis, lumbosacral region",Outpatient Hospital,2023-01-04,MR,72148,Mri lumbar spine w/o dye,740.00,1,2023Q1,1,61-70,501 to 1000,Other
4947,27279,65.0,Spondylopathies/spondyloarthropathy (including...,M4807,"Spinal stenosis, lumbosacral region",Outpatient Hospital,2023-01-04,MR,72148,Mri lumbar spine w/o dye,82.17,1,2023Q1,1,61-70,0 to 100,Other
12660,25650,65.0,Other specified bone disease and musculoskelet...,M8589,Other specified disorders of bone density and ...,Outpatient Hospital,2023-01-06,Standard X-ray,77080,Dxa bone density axial,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
13032,17559,65.0,Osteoarthritis,M19011,"Primary osteoarthritis, right shoulder",Outpatient Hospital,2023-01-07,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
12126,52374,65.0,"Musculoskeletal pain, not low back pain",M79672,Pain in left foot,Ambulatory Surgical Center,2023-01-08,Standard X-ray,77071,X-ray stress view,63.95,1,2023Q1,1,61-70,0 to 100,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1946,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,71100,X-ray exam ribs uni 2 views,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
2232,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
2849,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,72070,X-ray exam thorac spine 2vws,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
3625,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,72040,X-ray exam neck spine 2-3 vw,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
11757,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,71046,X-ray exam chest 2 views,160.00,1,2023Q1,1,71-80,101 to 250,X Ray

In [58]:
#Sort by descending
filtered_imaging_df = filtered_imaging_df.sort_values(by=['Person_Age', 'Service_Date'], ascending=False)
filtered_imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
1946,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,71100,X-ray exam ribs uni 2 views,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
2232,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
2849,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,72070,X-ray exam thorac spine 2vws,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
3625,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,72040,X-ray exam neck spine 2-3 vw,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
11757,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,71046,X-ray exam chest 2 views,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12126,52374,65.0,"Musculoskeletal pain, not low back pain",M79672,Pain in left foot,Ambulatory Surgical Center,2023-01-08,Standard X-ray,77071,X-ray stress view,63.95,1,2023Q1,1,61-70,0 to 100,X Ray
13032,17559,65.0,Osteoarthritis,M19011,"Primary osteoarthritis, right shoulder",Outpatient Hospital,2023-01-07,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
12660,25650,65.0,Other specified bone disease and musculoskelet...,M8589,Other specified disorders of bone density and ...,Outpatient Hospital,2023-01-06,Standard X-ray,77080,Dxa bone density axial,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
1405,27279,65.0,Spondylopathies/spondyloarthropathy (including...,M4807,"Spinal stenosis, lumbosacral region",Outpatient Hospital,2023-01-04,MR,72148,Mri lumbar spine w/o dye,740.00,1,2023Q1,1,61-70,501 to 1000,Other
4947,27279,65.0,Spondylopathies/spondyloarthropathy (including...,M4807,"Spinal stenosis, lumbosacral region",Outpatient Hospital,2023-01-04,MR,72148,Mri lumbar spine w/o dye,82.17,1,2023Q1,1,61-70,0 to 100,Other

In [59]:
#Sort Person_Age by ascending and Service_Date by descending
filtered_imaging_df = filtered_imaging_df.sort_values(by=['Person_Age', 'Service_Date'], ascending=[False,True])
filtered_imaging_df

,Person_Id,Person_Age,Diagnosis_Group,Diagnosis_Code,Diagnosis_Description,Place_of_Service_Description,Service_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
1946,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,71100,X-ray exam ribs uni 2 views,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
2232,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,73030,X-ray exam of shoulder,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
2849,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,72070,X-ray exam thorac spine 2vws,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
3625,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,72040,X-ray exam neck spine 2-3 vw,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
11757,1240,77.0,"Musculoskeletal pain, not low back pain",M25511,Pain in right shoulder,Outpatient Hospital,2023-01-28,Standard X-ray,71046,X-ray exam chest 2 views,160.00,1,2023Q1,1,71-80,101 to 250,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12948,22665,65.0,Other specified connective tissue disease,M7732,"Calcaneal spur, left foot",Outpatient Hospital,2023-01-22,Standard X-ray,73610,X-ray exam of ankle,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
4396,25103,65.0,Osteoarthritis,M1712,"Unilateral primary osteoarthritis, left knee",Outpatient Hospital,2023-01-26,Standard X-ray,73560,X-ray exam of knee 1 or 2,160.00,1,2023Q1,1,61-70,101 to 250,X Ray
7212,52891,65.0,Osteoarthritis,M19012,"Primary osteoarthritis, left shoulder",Office,2023-01-26,Standard X-ray,73030,X-ray exam of shoulder,43.09,1,2023Q1,1,61-70,0 to 100,X Ray
3627,25103,65.0,"Musculoskeletal pain, not low back pain",M25562,Pain in left knee,Office,2023-01-27,Standard X-ray,73564,X-ray exam knee 4 or more,110.64,2,2023Q1,1,61-70,101 to 250,X Ray
12835,25103,65.0,"Musculoskeletal pain, not low back pain",M25562,Pain in left knee,Office,2023-01-27,Standard X-ray,73564,X-ray exam knee 4 or more,55.32,1,2023Q1,1,61-70,0 to 100,X Ray

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Update DataFrame - Renaming Columns
Many times, we get data with names that don’t follow our naming conventions or are just not that useful or meaningful. Therefore, we rename them.
### `df.rename(mapper=None, index=None, columns=None, axis=None)`
   
Key points:
 - Parameters:
    - mapper (default: None): A mapping function or dictionary for renaming index or columns.
    - index (default: None): Dictionary-like or function to rename specific index labels. Example: index={'Row1': 'First_Row', 'Row2': 'Second_Row'}
    - columns (default: None): Dictionary-like or function to rename specific column labels. Example: {'Old_Name': 'New_Name'}.
    - axis (default: None): Axis to apply renaming:
        - 0 or 'index': Rename index.
        - 1 or 'columns': Rename columns.
</div>

In [60]:
imaging_df = imaging_df.rename(
columns = {
    'Service_Date':'Image_Date',
    'Diagnosis_Code':'IC10_Code'
}
)
imaging_df.columns

Index(['Person_Id', 'Person_Age', 'Diagnosis_Group', 'IC10_Code',
       'Diagnosis_Description', 'Place_of_Service_Description', 'Image_Date',
       'Procedure_Group', 'Procedure_Code', 'Procedure_Description', 'Cost',
       'Quantity', 'Year_Qtr', 'Service_Month', 'Person_Age_Group',
       'Cost_Buckets', 'X_Ray_Grouper'],
      dtype='object')

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Update DataFrame - Drop Columns
Many times, we get columns of data that is incomplete, bad, or completely empty. Therefore, we can drop them.
Note - Make a copy of the original DataFrame before you start changing things (such as dropping columns, renaming, or manipulating the data).Good practice when working with a new set of data.     
### `df.drop(labels=None, axis=1, columns=None, level=None)`
   
Key points:
 - Parameters:
    - labels (default: None): Specifies the name(s) of the row or column labels to drop. Use with axis to determine whether to drop rows (axis=0) or columns (axis=1).
    - columns (default: None): Specifies the name(s) of columns to drop. Use this instead of labels when specifically targeting columns.
    - axis (default: 0): Specifies whether to drop rows (axis=0) or columns (axis=1). Not needed when columns or labels is explicitly provided.
    - level (default: None): Used for dropping labels in a specified level in MultiIndex.
</div>

In [61]:
imaging_df_copy = imaging_df.copy()
#Drop Person Age since I created a Person Age Group column
imaging_df_copy = imaging_df_copy.drop(columns=['Person_Age'])
imaging_df_copy

,Person_Id,Diagnosis_Group,IC10_Code,Diagnosis_Description,Place_of_Service_Description,Image_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
0,40985,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,2022-09-24,Standard X-ray,73030,X-ray exam of shoulder,63.40,1,2022Q3,9,31-40,0 to 100,X Ray
1,55043,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,2023-01-30,Ultrasound,93306,Tte w/doppler complete,95.70,1,2023Q1,1,NA,0 to 100,Other
2,59784,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2023-02-01,Standard X-ray,73630,X-ray exam of foot,160.00,1,2023Q1,2,NA,101 to 250,X Ray
3,31182,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,2022-04-29,Standard X-ray,73560,X-ray exam of knee 1 or 2,63.40,1,2022Q2,4,41-50,0 to 100,X Ray
4,15640,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,2022-06-19,Standard X-ray,73630,X-ray exam of foot,63.40,1,2022Q2,6,41-50,0 to 100,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13180,22205,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,2022-12-18,Ultrasound,93971,Extremity study,691.60,1,2022Q4,12,41-50,501 to 1000,Other
13181,39950,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,2022-01-10,CT Scan,72125,Ct neck spine w/o dye,64.31,1,2022Q1,1,61-70,0 to 100,Other
13182,35619,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,2022-01-17,Standard X-ray,73560,X-ray exam of knee 1 or 2,95.00,1,2022Q1,1,41-50,0 to 100,X Ray
13183,39682,Low back pain,M545,Low back pain,Outpatient Hospital,2022-08-21,Standard X-ray,72114,X-ray exam l-s spine bending,146.41,1,2022Q3,8,51-60,101 to 250,X Ray
13184,31303,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,2022-12-28,Standard X-ray,73110,X-ray exam of wrist,63.40,1,2022Q4,12,61-70,0 to 100,X Ray

<div style="background-color: #9DC9D5; padding: 10px; border-radius: 8px;">
    
## Update DataFrame - Replace Data
Many times, can get multiple values for the same data. We may want to take the time and clean up some of these variations or even create a new name. Therefore, we can use replace.
    
### `df['Column_Name'].replace(to_replace, value)`
   
Key points:
 - Parameters:
    - df['Column_Name']: Specifies the column where the replacement will occur.
    - to_replace: The value(s) to be replaced. Can be a single value, list, dictionary, or regular expression.
        - Example:
        - Single value: "Old_Value"
        - Multiple values: ["Old_Value1", "Old_Value2"]
        - Dictionary: {"Old_Value1": "New_Value1", "Old_Value2": "New_Value2"}
    - value: The new value(s) to replace the old ones. Corresponds to to_replace.
</div>

In [62]:
#I want to shorten the name Standard X-ray in my Procedure Group column to X-ray. This will help when we begin creating pivots and different types of plots, charts, and graphs.
imaging_df['Procedure_Group'] = imaging_df['Procedure_Group'].replace("Standard X-ray", "X-Ray")
imaging_df

,Person_Id,Person_Age,Diagnosis_Group,IC10_Code,Diagnosis_Description,Place_of_Service_Description,Image_Date,Procedure_Group,Procedure_Code,Procedure_Description,Cost,Quantity,Year_Qtr,Service_Month,Person_Age_Group,Cost_Buckets,X_Ray_Grouper
0,40985,37.0,"Musculoskeletal pain, not low back pain",M2550,Pain in unspecified joint,Outpatient Hospital,2022-09-24,X-Ray,73030,X-ray exam of shoulder,63.40,1,2022Q3,9,31-40,0 to 100,X Ray
1,55043,0.0,Systemic lupus erythematosus and connective ti...,M303,Mucocutaneous lymph node syndrome [Kawasaki],Inpatient Hospital,2023-01-30,Ultrasound,93306,Tte w/doppler complete,95.70,1,2023Q1,1,NA,0 to 100,Other
2,59784,0.0,"Musculoskeletal pain, not low back pain",M79671,Pain in right foot,Outpatient Hospital,2023-02-01,X-Ray,73630,X-ray exam of foot,160.00,1,2023Q1,2,NA,101 to 250,X Ray
3,31182,43.0,"Musculoskeletal pain, not low back pain",M25561,Pain in right knee,Outpatient Hospital,2022-04-29,X-Ray,73560,X-ray exam of knee 1 or 2,63.40,1,2022Q2,4,41-50,0 to 100,X Ray
4,15640,49.0,"Musculoskeletal pain, not low back pain",M79675,Pain in left toe(s),Outpatient Hospital,2022-06-19,X-Ray,73630,X-ray exam of foot,63.40,1,2022Q2,6,41-50,0 to 100,X Ray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13180,22205,41.0,"Musculoskeletal pain, not low back pain",M79661,Pain in right lower leg,Outpatient Hospital,2022-12-18,Ultrasound,93971,Extremity study,691.60,1,2022Q4,12,41-50,501 to 1000,Other
13181,39950,64.0,Spondylopathies/spondyloarthropathy (including...,M542,Cervicalgia,Emergency Room – Hospital,2022-01-10,CT Scan,72125,Ct neck spine w/o dye,64.31,1,2022Q1,1,61-70,0 to 100,Other
13182,35619,47.0,Other specified joint disorders,M25861,"Other specified joint disorders, right knee",Outpatient Hospital,2022-01-17,X-Ray,73560,X-ray exam of knee 1 or 2,95.00,1,2022Q1,1,41-50,0 to 100,X Ray
13183,39682,58.0,Low back pain,M545,Low back pain,Outpatient Hospital,2022-08-21,X-Ray,72114,X-ray exam l-s spine bending,146.41,1,2022Q3,8,51-60,101 to 250,X Ray
13184,31303,61.0,"Musculoskeletal pain, not low back pain",M25532,Pain in left wrist,Outpatient Hospital,2022-12-28,X-Ray,73110,X-ray exam of wrist,63.40,1,2022Q4,12,61-70,0 to 100,X Ray